//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public string Beneficiary_Name { get; set; }
        public Nullable<int> Beneficiary_Account_Number { get; set; }
        public string Save_Status { get; set; }
        public string Nick_Name { get; set; }
        public Nullable<int> Holder_Account_Number { get; set; }
        public int beniid { get; set; }
    }
}
